# Makefile for GNU make

.PHONY: all 25_uniform_fog .DEFAULT 

all: 25_uniform_fog 

25_uniform_fog:
	$(MAKE) -f Makefile.25_uniform_fog 25_uniform_fog

.DEFAULT:
	$(MAKE) -f Makefile.25_uniform_fog $@

