# Makefile for GNU make

.PHONY: all 07_two_texture_accesses .DEFAULT 

all: 07_two_texture_accesses 

07_two_texture_accesses:
	$(MAKE) -f Makefile.07_two_texture_accesses 07_two_texture_accesses

.DEFAULT:
	$(MAKE) -f Makefile.07_two_texture_accesses $@

