# Makefile for GNU make

.PHONY: all vertex_texture .DEFAULT 

all: vertex_texture 

vertex_texture:
	$(MAKE) -f Makefile.vertex_texture vertex_texture

.DEFAULT:
	$(MAKE) -f Makefile.vertex_texture $@

