# Makefile for GNU make

.PHONY: all 18_cube_map_reflection .DEFAULT 

all: 18_cube_map_reflection 

18_cube_map_reflection:
	$(MAKE) -f Makefile.18_cube_map_reflection 18_cube_map_reflection

.DEFAULT:
	$(MAKE) -f Makefile.18_cube_map_reflection $@

