# Makefile for GNU make

.PHONY: all 08_vertex_transform .DEFAULT 

all: 08_vertex_transform 

08_vertex_transform:
	$(MAKE) -f Makefile.08_vertex_transform 08_vertex_transform

.DEFAULT:
	$(MAKE) -f Makefile.08_vertex_transform $@

