# Makefile for GNU make

.PHONY: all 22_specular_bump_map .DEFAULT 

all: 22_specular_bump_map 

22_specular_bump_map:
	$(MAKE) -f Makefile.22_specular_bump_map 22_specular_bump_map

.DEFAULT:
	$(MAKE) -f Makefile.22_specular_bump_map $@

