# Makefile for GNU make

.PHONY: all 20_chromatic_dispersion .DEFAULT 

all: 20_chromatic_dispersion 

20_chromatic_dispersion:
	$(MAKE) -f Makefile.20_chromatic_dispersion 20_chromatic_dispersion

.DEFAULT:
	$(MAKE) -f Makefile.20_chromatic_dispersion $@

