# Makefile for GNU make

.PHONY: all 16_keyframe_interpolation .DEFAULT 

all: 16_keyframe_interpolation 

16_keyframe_interpolation:
	$(MAKE) -f Makefile.16_keyframe_interpolation 16_keyframe_interpolation

.DEFAULT:
	$(MAKE) -f Makefile.16_keyframe_interpolation $@

