# Makefile for GNU make

.PHONY: all 05_texture_sampling .DEFAULT 

all: 05_texture_sampling 

05_texture_sampling:
	$(MAKE) -f Makefile.05_texture_sampling 05_texture_sampling

.DEFAULT:
	$(MAKE) -f Makefile.05_texture_sampling $@

