# Makefile for GNU make

.PHONY: all 21_bump_map_wall .DEFAULT 

all: 21_bump_map_wall 

21_bump_map_wall:
	$(MAKE) -f Makefile.21_bump_map_wall 21_bump_map_wall

.DEFAULT:
	$(MAKE) -f Makefile.21_bump_map_wall $@

