# Makefile for GNU make

.PHONY: all 01_vertex_program .DEFAULT 

all: 01_vertex_program 

01_vertex_program:
	$(MAKE) -f Makefile.01_vertex_program 01_vertex_program

.DEFAULT:
	$(MAKE) -f Makefile.01_vertex_program $@

