# Makefile for GNU make

.PHONY: all 27_projective_texturing .DEFAULT 

all: 27_projective_texturing 

27_projective_texturing:
	$(MAKE) -f Makefile.27_projective_texturing 27_projective_texturing

.DEFAULT:
	$(MAKE) -f Makefile.27_projective_texturing $@

