# Makefile for GNU make

.PHONY: all 19_cube_map_refraction .DEFAULT 

all: 19_cube_map_refraction 

19_cube_map_refraction:
	$(MAKE) -f Makefile.19_cube_map_refraction 19_cube_map_refraction

.DEFAULT:
	$(MAKE) -f Makefile.19_cube_map_refraction $@

