.de Sh \" Subsection heading
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp \" Vertical space (when we can't use .PP)
.if t .sp .5v
.if n .sp
..
.de Vb \" Begin verbatim text
.ft CW
.nf
.ne \\$1
..
.de Ve \" End verbatim text
.ft R
.fi
..
.tr \(*W-
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.ie n \{\
.    ds -- \(*W-
.    ds PI pi
.    if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.    if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\"  diablo 12 pitch
.    ds L" ""
.    ds R" ""
.    ds C` ""
.    ds C' ""
'br\}
.el\{\
.    ds -- \|\(em\|
.    ds PI \(*p
.    ds L" ``
.    ds R" ''
'br\}
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ie \nF \{\
.    de IX
.    tm Index:\\$1\t\\n%\t"\\$2"
..
.    nr % 0
.    rr F
.\}
.el \{\
.    de IX
..
.\}
.    \" fudge factors for nroff and troff
.if n \{\
.    ds #H 0
.    ds #V .8m
.    ds #F .3m
.    ds #[ \f1
.    ds #] \fP
.\}
.if t \{\
.    ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.    ds #V .6m
.    ds #F 0
.    ds #[ \&
.    ds #] \&
.\}
.    \" simple accents for nroff and troff
.if n \{\
.    ds ' \&
.    ds ` \&
.    ds ^ \&
.    ds , \&
.    ds ~ ~
.    ds /
.\}
.if t \{\
.    ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.    ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.    ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.    ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.    ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.    ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.\}
.    \" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.    \" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.    \" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.    ds : e
.    ds 8 ss
.    ds o a
.    ds d- d\h'-1'\(ga
.    ds D- D\h'-1'\(hy
.    ds th \o'bp'
.    ds Th \o'LP'
.    ds ae ae
.    ds Ae AE
.\}
.rm #[ #] #H #V #F C
.IX Title "cgCreateProgram 3"
.TH cgCreateProgram 3 "Cg Toolkit 3.0" "perl v5.10.0" "Cg Core Runtime API"
.if n .ad l
.nh
.SH "NAME"
\&\fBcgCreateProgram\fR \- create a program object from a string
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
.Vb 1
\&  #include <Cg/cg.h>
\&
\&  CGprogram cgCreateProgram( CGcontext context, 
\&                             CGenum program_type,
\&                             const char * program,
\&                             CGprofile profile,
\&                             const char * entry,
\&                             const char ** args );
.Ve
.SH "PARAMETERS"
.IX Header "PARAMETERS"
.IP "context" 8
.IX Item "context"
The context to which the new program will be added.
.IP "program_type" 8
.IX Item "program_type"
An enumerant describing the contents of the \fBprogram\fR string.
The following enumerants are allowed:
.RS 8
.IP "\fB\s-1CG_SOURCE\s0\fR" 4
.IX Item "CG_SOURCE"
\&\fBprogram\fR contains Cg source code.
.IP "\fB\s-1CG_OBJECT\s0\fR" 4
.IX Item "CG_OBJECT"
\&\fBprogram\fR contains object code that resulted from the precompilation
of some Cg source code.
.RE
.RS 8
.RE
.IP "program" 8
.IX Item "program"
A string containing either the programs source or object code.
See \fBprogram_type\fR for more information.
.IP "profile" 8
.IX Item "profile"
The profile enumerant for the program.
.IP "entry" 8
.IX Item "entry"
The entry point to the program in the Cg source.  If \fB\s-1NULL\s0\fR, the entry
point defaults to "\fBmain\fR".
.IP "args" 8
.IX Item "args"
If \fBargs\fR is not \fB\s-1NULL\s0\fR it is assumed to be an array of NULL-terminated 
strings that will be passed directly to the compiler as arguments.  The
last value of the array must be a \fB\s-1NULL\s0\fR.
.SH "RETURN VALUES"
.IX Header "RETURN VALUES"
Returns a \fBCGprogram\fR handle on success.
.PP
Returns \fB\s-1NULL\s0\fR if an error occurs.
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
cgCreateProgram generates a new \fBCGprogram\fR object and adds
it to the specified Cg context.
.SH "EXAMPLES"
.IX Header "EXAMPLES"
.Vb 7
\&  CGcontext context = cgCreateContext();
\&  CGprogram program = cgCreateProgram(context,
\&                                      CG_SOURCE,
\&                                      mysourcestring,
\&                                      CG_PROFILE_ARBVP1,
\&                                      "myshader",
\&                                      NULL);
.Ve
.SH "ERRORS"
.IX Header "ERRORS"
\&\fB\s-1CG_INVALID_CONTEXT_HANDLE_ERROR\s0\fR is generated if \fBcontext\fR is not a valid context.
.PP
\&\fB\s-1CG_INVALID_ENUMERANT_ERROR\s0\fR is generated if \fBprogram_type\fR is not
\&\fB\s-1CG_SOURCE\s0\fR or \fB\s-1CG_OBJECT\s0\fR.
.PP
\&\fB\s-1CG_UNKNOWN_PROFILE_ERROR\s0\fR is generated if \fBprofile\fR is not a supported profile.
.PP
\&\fB\s-1CG_COMPILER_ERROR\s0\fR is generated if compilation fails.
.SH "HISTORY"
.IX Header "HISTORY"
\&\fBcgCreateProgram\fR was introduced in Cg 1.1.
.SH "SEE ALSO"
.IX Header "SEE ALSO"
cgCreateContext,
cgCreateProgramFromFile,
cgDestroyProgram,
cgGetProgramString
