# -*- mode:python -*-

# Copyright (c) 2011 Mark D. Hill and David A. Wood
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#


Import('*')

Source('addrdec.cc', Werror=False)
Source('dram.cc', Werror=False)
Source('dram_sched.cc', Werror=False)
Source('gpu-cache.cc', Werror=False)
Source('gpu-cache_gem5.cc', Werror=False)
Source('gpu-misc.cc', Werror=False)
Source('gpu-sim.cc', Werror=False)
Source('histogram.cc', Werror=False)
Source('icnt_wrapper.cc', Werror=False)
Source('l2cache.cc', Werror=False)
Source('mem_fetch.cc', Werror=False)
Source('mem_latency_stat.cc', Werror=False)
Source('power_stat.cc', Werror=False)
Source('scoreboard.cc', Werror=False)
Source('shader.cc', Werror=False)
Source('stack.cc', Werror=False)
Source('stat-tool.cc', Werror=False)
Source('traffic_breakdown.cc', Werror=False)
Source('visualizer.cc', Werror=False)

#Source('fq_push_m5.cc')

