# Makefile for GNU make

.PHONY: all 15_particle_system .DEFAULT 

all: 15_particle_system 

15_particle_system:
	$(MAKE) -f Makefile.15_particle_system 15_particle_system

.DEFAULT:
	$(MAKE) -f Makefile.15_particle_system $@

